server:
  port: 10000
spring:
  application:
    name: SCW-WEBUI
  redis:
    host: 192.168.163.129
    port: 6379
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #开发的时候禁用缓存

logging:
  file: D:\logs\scw-webui.log
  level:
    com.dragon.scw: debug

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

