spring:
  application:
    name: SCW-PROJECT
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.163.129:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
  redis:
    host: 192.168.163.129
    port: 6379
  servlet:
    multipart:
      #上传一个文件最大值  默认是1MB
      max-file-size: 10MB
      #上传多个文件最大值  默认是10MB
      max-request-size: 10MB
 
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true
 
server:
  port: 8000
  
logging:
  file: D:\logs\scw-project.log
  level:
    com.dragon.scw: debug
    
swagger2: 
  enable: true
  
#请填写你在阿里云申请的OSS信息
oss: 
  endpoint: 
  accessKeyId: 
  accessKeySecret: 
  bucket: 
