spring:
  application:
    name: SCW-ORDER 
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.163.129:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.163.129
    port: 6379


feign:
  hystrix:
    enabled: true
    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-ORDER
    prefer-ip-address: true
    
    
server:
  port: 9000
  
logging:
  file: D:\logs\scw-order.log
  level:
    com.dragon.scw: debug
    
swagger2: 
  enable: true
